// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StreetParking.API.DbContexts;

#nullable disable

namespace StreetParking.API.Migrations
{
    [DbContext(typeof(StreetParkingContext))]
    [Migration("20230911012904_creating tables")]
    partial class creatingtables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("StreetParking.API.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Test Descriptions",
                            Name = "Test"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Test Description 2",
                            Name = "Test 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Test description 2",
                            Name = "Test 3"
                        });
                });

            modelBuilder.Entity("StreetParking.API.Entities.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PointOfInterests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "A beautiful green space for relaxation.",
                            Name = "Park"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 2,
                            Description = "A beautiful green space for relaxation.",
                            Name = "Park"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 3,
                            Description = "A beautiful green space for relaxation.",
                            Name = "Park"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 1,
                            Description = "A beautiful green space for relaxation.",
                            Name = "Park"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 1,
                            Description = "A beautiful green space for relaxation.",
                            Name = "Park"
                        });
                });

            modelBuilder.Entity("StreetParking.API.Entities.PointOfInterest", b =>
                {
                    b.HasOne("StreetParking.API.Entities.City", "City")
                        .WithMany("PointOfInterests")
                        .HasForeignKey("CityId");

                    b.Navigation("City");
                });

            modelBuilder.Entity("StreetParking.API.Entities.City", b =>
                {
                    b.Navigation("PointOfInterests");
                });
#pragma warning restore 612, 618
        }
    }
}
